# Renovate configuration validator
#
# This workflow validates changes proposed into Renovate configuration file,
# located .github/renovate.json5.
#
# Key Features:
# - Validate changes and prevent non-valid configuration to be used by Renovate.
#
# Process Stages:
# Configuration validation:
#    - Runs on PR into .github/renovate.json5 and validate changes.
#
# Required Secrets:
# - None
#
# Example Usage:
# Automatically triggered on:
# - Pull requests to .github/renovate.json5.
#
# Note: None.

name: Validate Renovate configuration

on:
  pull_request:
    paths:
      - ".github/renovate.json5"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout configuration
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Validate configuration
        run: |
          # renovate: datasource=docker
          export RENOVATE_IMAGE=ghcr.io/renovatebot/renovate:40.11
          docker run --rm --entrypoint "renovate-config-validator" \
          -v "${{ github.workspace }}/.github/renovate.json5":"/renovate.json5" \
          ${RENOVATE_IMAGE} "/renovate.json5"
